name: pull request workflow
on: pull_request

jobs:

  reusable-pr-workflow:
    uses: pentaho/mondrian/.github/workflows/common_pr.yaml@threatrix
    with:
      slack_channels: ""
#      sonar_project_key: "pdi-plugins-ee"
      additional_mvn_directives: ""
      # add pentaho legacy scpid
      threatrix_scpid: 3ef4b1f1-778b-4204-94ae-5c7e360f13ab
    secrets: inherit
