name: pull request workflow
on: pull_request

jobs:

  reusable-pr-workflow:
    uses: pentaho/actions-common/.github/workflows/pr.yml@HNC-853
    with:
      slack_channels: ""
#      sonar_project_key: "pdi-plugins-ee"
      additional_mvn_directives: ""
    secrets: inherit
